# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple_memoize}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Danger Canty"]
  s.date = %q{2011-04-10}
  s.email = %q{rubygems@6brand.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.txt"
  ]
  s.files = [
    "LICENSE",
    "README.txt",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/simple_memoize.rb",
    "rails/init.rb",
    "simple_memoize.gemspec",
    "test/test_simple_memoize.rb"
  ]
  s.homepage = %q{http://github.com/JackDanger/simple_memoize}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Very lightweight way to ensure some methods only run once}
  s.test_files = [
    "test/test_simple_memoize.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

